import {
  Beaker,
  Box,
  Clipboard,
  Cpu,
  Droplets,
  FileCheck,
  FileCog,
  Flame,
  FlaskConical,
  FlaskRound,
  Gauge,
  Package,
  Radio,
  Sparkles,
  Syringe,
  TestTube,
  TestTube2,
  TrendingUp,
  User,
  Waves,
  Wind,
  Wrench,
  Zap,
} from 'lucide-react'

export const formSteps = [
  { number: 1, title: 'Dados do Operador', id: 'operator-data', icon: User },
  {
    number: 2,
    title: 'Informações da Caldeira',
    id: 'boiler-info',
    icon: Flame,
  },
  {
    number: 3,
    title: 'Estrutura do Forno',
    id: 'structure-furnace',
    icon: Box,
  },
  {
    number: 4,
    title: 'Estrutura do Espelho',
    id: 'structure-mirror',
    icon: Sparkles,
  },
  {
    number: 5,
    title: 'Estrutura do Corpo',
    id: 'structure-body',
    icon: Package,
  },
  { number: 6, title: 'Estrutura dos Tubos', id: 'structure-tube', icon: Wind },
  { number: 7, title: 'Testes Gerais', id: 'general-tests', icon: TestTube2 },
  { number: 8, title: 'Testes Externos', id: 'external-tests', icon: Wrench },
  { number: 9, title: 'Testes Internos', id: 'internal-tests', icon: TestTube },
  {
    number: 10,
    title: 'Testes Instalação Local',
    id: 'local-installation-tests',
    icon: TrendingUp,
  },
  { number: 11, title: 'Injetor', id: 'injector', icon: Syringe },
  { number: 12, title: 'Alimentação Elétrica', id: 'power-supply', icon: Zap },
  {
    number: 13,
    title: 'Indicador de Nível',
    id: 'level-indicator',
    icon: Gauge,
  },
  {
    number: 14,
    title: 'Testes de Válvulas',
    id: 'valve-tests',
    icon: FlaskConical,
  },
  {
    number: 15,
    title: 'Ordem de Calibração',
    id: 'calibration-order',
    icon: Clipboard,
  },
  { number: 16, title: 'Painel Eletrônico', id: 'eletronic-panel', icon: Cpu },
  {
    number: 17,
    title: 'Sistema de Descarga',
    id: 'discharge-system',
    icon: Droplets,
  },
  { number: 18, title: 'Qualidade da Água', id: 'water-quality', icon: Beaker },
  {
    number: 19,
    title: 'Teste Hidrostático',
    id: 'hidrostatic-test',
    icon: Waves,
  },
  {
    number: 20,
    title: 'Teste de Acumulação',
    id: 'accumulation-test',
    icon: FlaskRound,
  },
  {
    number: 21,
    title: 'Teste de Ultrassom',
    id: 'ultrasound-test',
    icon: Radio,
  },
  { number: 22, title: 'PMTA', id: 'pmta', icon: FileCog },
  { number: 23, title: 'Conclusões', id: 'conclusions', icon: FileCheck },
]
